### 聚类生成anchor box

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import xml.dom.minidom
import os

In [2]:
X = np.array([[1, 2], [1, 4], [1, 0],
               [4, 2], [4, 4], [4, 0]])
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
print(kmeans.labels_)
kmeans.predict([[0, 0], [4, 4]])
print(kmeans.cluster_centers_)

[0 0 0 1 1 1]
[[1. 2.]
 [4. 2.]]


In [20]:
root_dir = "/home/sakulaki/1216_origin/tct_data1216/"
selected_class = ["ASCUS", "LSIL", "ASCH", "HSIL", "SCC"]

xml_file_dirs = os.listdir(root_dir)

xml_file_list = []
for xml_file_dir in xml_file_dirs:
    temp_xml_file_list = os.listdir(root_dir + xml_file_dir)
    for i, xml_file in enumerate(temp_xml_file_list):
        temp_xml_file_list[i] = root_dir + xml_file_dir + "/" + xml_file
    xml_file_list += temp_xml_file_list
    
for i, xml_file in enumerate(xml_file_list):
    xml_file_list[i] = xml_file.split(".")[0]

xml_file_list = list(set(xml_file_list))

for i, xml_file in enumerate(xml_file_list):
    xml_file_list[i] = xml_file + ".xml"

In [23]:
def parse_xml_gen_data(xml_name, box_data, selected_classes):
    DOMTree = xml.dom.minidom.parse(xml_name)
    collection = DOMTree.documentElement
    filename = collection.getElementsByTagName("filename")
    objects = collection.getElementsByTagName("object")
    
    w = collection.getElementsByTagName("width")[0]
    w_val = int(w.firstChild.nodeValue)
    h = collection.getElementsByTagName("height")[0]
    h_val = int(h.firstChild.nodeValue)
    w.firstChild.replaceWholeText(str(h_val))
    h.firstChild.replaceWholeText(str(w_val))
    
    for object in objects:
        if object.getElementsByTagName("name")[0].firstChild.nodeValue in selected_classes:
            xmin = object.getElementsByTagName("xmin")[0]
            xmin_val = int(xmin.firstChild.nodeValue)
            xmax = object.getElementsByTagName("xmax")[0]
            xmax_val = int(xmax.firstChild.nodeValue)
            ymin = object.getElementsByTagName("ymin")[0]
            ymin_val = int(ymin.firstChild.nodeValue)
            ymax = object.getElementsByTagName("ymax")[0]
            ymax_val = int(ymax.firstChild.nodeValue)
        
            box_h = ymax_val - ymin_val
            box_w = xmax_val - xmin_val
        
            box_data.append([box_w, box_h])

In [25]:
box_data = []
count = 0

for i in range(int(len(xml_file_list)/1000)):
    for xml_file_path in xml_file_list[i * 1000:(i + 1) * 1000]:
        parse_xml_gen_data(xml_file_path, box_data, selected_class)
    count += 1
    print(count)
    if (i == (int(len(xml_file_list)/1000) - 1)):
        for xml_file_path in xml_file_list[(i + 1) * 1000:]:
            parse_xml_gen_data(xml_file_path, box_data, selected_class)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22


In [26]:
print(len(box_data))

36482


In [27]:
print(box_data)

[[136, 145], [217, 178], [57, 64], [59, 55], [46, 84], [66, 74], [84, 79], [89, 61], [57, 80], [104, 56], [71, 62], [95, 67], [75, 62], [88, 114], [38, 55], [61, 70], [51, 56], [54, 82], [60, 97], [188, 221], [219, 219], [80, 97], [128, 143], [185, 151], [99, 127], [48, 67], [50, 53], [73, 71], [60, 93], [50, 68], [61, 122], [51, 63], [60, 64], [57, 49], [501, 368], [193, 275], [68, 73], [63, 55], [74, 76], [58, 47], [56, 70], [79, 46], [84, 67], [155, 186], [90, 88], [100, 90], [101, 98], [113, 96], [41, 62], [69, 136], [81, 104], [78, 80], [193, 177], [229, 277], [249, 173], [104, 80], [135, 107], [54, 80], [128, 149], [217, 275], [116, 131], [354, 243], [66, 72], [82, 57], [64, 78], [59, 54], [65, 66], [381, 250], [197, 166], [387, 244], [163, 139], [133, 160], [104, 116], [85, 84], [61, 78], [90, 87], [210, 208], [162, 156], [151, 158], [364, 286], [322, 255], [167, 213], [267, 377], [184, 142], [495, 378], [178, 335], [291, 201], [179, 301], [96, 78], [84, 76], [62, 58], [50, 36],

In [28]:
X = np.array(box_data)
kmeans = KMeans(n_clusters = 9, random_state= 1).fit(X)
print(kmeans.cluster_centers_ / 2)


[[ 53.91792849  52.81168088]
 [189.67193426 234.51011378]
 [131.002104   102.78268711]
 [ 33.38570418  32.65682944]
 [397.19704433 379.23399015]
 [195.13651102 149.15175097]
 [119.93899959 150.50427003]
 [299.19107744 236.07407407]
 [ 86.33584364  88.07495069]]


In [84]:
a = [1,2,3,4,5]
print(a[0:1])
print(a[1:2])
print(a[2:])

[1]
[2]
[3, 4, 5]
